version: '3.7'
services:
    postgres:
        image: postgres:10.5
        container_name: polar-postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=polardb_catalog
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data:z
          # copy the sql script to create tables
          - ./postgres:/docker-entrypoint-initdb.d

    adminer:
      image: adminer
      container_name: adminer
      ports:
        - '9090:8080'
      depends_on:
        - postgres