version: '2.1'

services:

# Applications

  config-service:
    image: ernestoacostacuba/config-service:0.0.1-SNAPSHOT
    container_name: config-service
    ports:
      - '8888:8888'
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 9888
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888
    networks:
      - catalog-network

  catalog-service:
    image: ernestoacostacuba/catalog-service:0.0.1-SNAPSHOT
    container_name: catalog-service
    environment:
      BPL_DEBUG_ENABLED: "true"   # Activates the JVM configuration for accepting debug connections
      BPL_DEBUG_PORT: 8001      # Debug connections are accepted via a socket on port 8001
      BPL_JVM_THREAD_COUNT: 50
      SPRING_DATASOURCE_URL: jdbc:mysql://polar-mysql:3306/polardb_catalog?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_PROFILES_ACTIVE: 'mysqldev'
      DB_USER: 'catalog_user'
      DB_PASSWORD: 'TXlzcWwzMjFDYXRhbG9n'
      MYSQL_ROOT_PASSWORD: 'password'
      DB_HOST: 'polar-mysql'
      DB_NAME: ':polardb_catalog'
    ports:
      - '8001:8001' # The port where the JVM will listen for debug connections
      - '9001:9001'
    depends_on:
      polar-mysql:
        condition: service_healthy
    networks:
      - catalog-network

 # Backing Services

  polar-mysql:
    image: mysql:8.0
    container_name: polar-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./polar_mysql_db:/var/lib/mysql:z
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/1.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h",  "localhost"]
      timeout: 45s
      interval: 10s
      retries: 10
    depends_on:
      - config-service      
    networks:
      - catalog-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '9090:8080'
    depends_on:
      - polar-mysql
    networks:
      - catalog-network

volumes:
  my-db:
  polar_postgresql_db:

networks:
  catalog-network:
    driver: bridge