apiVersion: v1
kind: ConfigMap
metadata:
  name: polar-mysql-conf
data:
  polar-mysql-user: user
  polar-mysql-database: polardb_catalog
  polar-mysql-database-host: polar-mysql
  spring-r2dbc-url: r2dbc:mysql://polar-mysql:3306/polardb_catalog?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  spring-flyway-url: jdbc:mysql://polar-mysql:3306/polardb_catalog?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
